"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import {
  FolderKanban,
  Plus,
  Layers,
  Database,
  Play,
  Square,
  RotateCw,
  ExternalLink,
  Trash2,
  Globe,
  ArrowLeft,
  Sparkles,
  GitBranch,
  Wand2,
  Github,
  Upload,
  FileCode,
  Check,
  Key,
} from "lucide-react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Modal } from "@/components/ui/modal";
import { generateSslipDomain } from "@/lib/domain";

type SourceMode = "image" | "github_public" | "github_auth" | "zip" | "dockerfile";

export default function SingleProjectPage() {
  const params = useParams();
  const router = useRouter();
  const projectId = params.id as string;

  const [project, setProject] = useState<any>(null);
  const [serverIp, setServerIp] = useState<string>("127.0.0.1");
  const [isLoading, setIsLoading] = useState(true);

  // App Modal State
  const [isAppModalOpen, setIsAppModalOpen] = useState(false);
  const [appName, setAppName] = useState("");
  const [sourceMode, setSourceMode] = useState<SourceMode>("image");
  const [dockerImage, setDockerImage] = useState("nginx:alpine");
  const [gitRepository, setGitRepository] = useState("");
  const [gitBranch, setGitBranch] = useState("main");
  const [buildPack, setBuildPack] = useState("nixpacks");
  const [dockerfileContent, setDockerfileContent] = useState("FROM node:20-alpine\nWORKDIR /app\nCOPY . .\nRUN npm install\nCMD [\"npm\", \"start\"]");
  const [containerPort, setContainerPort] = useState("80");
  const [exposedPort, setExposedPort] = useState("");
  const [domain, setDomain] = useState("");
  const [zipFile, setZipFile] = useState<File | null>(null);

  // GitHub Auth / Repos State
  const [githubToken, setGithubToken] = useState("");
  const [githubRepos, setGithubRepos] = useState<any[]>([]);
  const [isLoadingRepos, setIsLoadingRepos] = useState(false);
  const [isCreatingApp, setIsCreatingApp] = useState(false);

  // Database Modal State
  const [isDbModalOpen, setIsDbModalOpen] = useState(false);
  const [dbName, setDbName] = useState("");
  const [dbType, setDbType] = useState<"postgres" | "mysql" | "redis" | "mongodb">("postgres");
  const [databaseName, setDatabaseName] = useState("");
  const [databaseUser, setDatabaseUser] = useState("");
  const [rootPassword, setRootPassword] = useState("");
  const [dbPort, setDbPort] = useState("");
  const [isCreatingDb, setIsCreatingDb] = useState(false);

  const fetchProject = async () => {
    try {
      const [projRes, statusRes] = await Promise.all([
        fetch(`/api/projects/${projectId}`),
        fetch(`/api/server/status`),
      ]);
      if (projRes.ok) {
        setProject(await projRes.json());
      } else {
        router.push("/projects");
      }
      if (statusRes.ok) {
        const s = await statusRes.json();
        if (s.serverIp) setServerIp(s.serverIp);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchProject();
  }, [projectId]);

  const handleFetchGithubRepos = async () => {
    if (!githubToken.trim()) return;
    setIsLoadingRepos(true);
    try {
      const res = await fetch("/api/github/repos", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token: githubToken }),
      });
      if (res.ok) {
        const data = await res.json();
        setGithubRepos(data.repos || []);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsLoadingRepos(false);
    }
  };

  const handleSelectRepo = (repo: any) => {
    setGitRepository(repo.cloneUrl);
    setGitBranch(repo.defaultBranch || "main");
    if (!appName) setAppName(repo.name.toLowerCase().replace(/[^a-z0-9-]/g, "-"));
  };

  const handleAutoGenerateDomain = () => {
    if (!appName.trim()) {
      setAppName("app-" + Math.floor(Math.random() * 1000));
    }
    const targetName = appName.trim() || "app-" + Math.floor(Math.random() * 1000);
    setDomain(generateSslipDomain(targetName, serverIp));
  };

  const handleCreateApp = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!appName.trim()) return;

    setIsCreatingApp(true);
    try {
      const finalDomain = domain.trim() || generateSslipDomain(appName, serverIp);

      let appTypePayload = "image";
      if (sourceMode === "github_public" || sourceMode === "github_auth") appTypePayload = "git";
      if (sourceMode === "dockerfile") appTypePayload = "dockerfile";

      const res = await fetch("/api/applications", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          projectId,
          name: appName,
          appType: appTypePayload,
          buildPack: appTypePayload === "git" ? buildPack : undefined,
          dockerImage: sourceMode === "image" ? dockerImage : undefined,
          gitRepository: (sourceMode === "github_public" || sourceMode === "github_auth") ? gitRepository : undefined,
          gitBranch,
          dockerfile: sourceMode === "dockerfile" ? dockerfileContent : undefined,
          containerPort: parseInt(containerPort, 10) || 80,
          exposedPort: exposedPort ? parseInt(exposedPort, 10) : undefined,
          domain: finalDomain,
        }),
      });

      if (res.ok) {
        const createdApp = await res.json();

        // If ZIP archive was selected, upload and extract zip
        if (sourceMode === "zip" && zipFile) {
          const zipData = new FormData();
          zipData.append("file", zipFile);
          await fetch(`/api/applications/${createdApp.id}/upload-zip`, {
            method: "POST",
            body: zipData,
          });
        } else {
          // Auto trigger initial deploy
          await fetch(`/api/applications/${createdApp.id}/deploy`, { method: "POST" });
        }

        setIsAppModalOpen(false);
        setAppName("");
        setDockerImage("nginx:alpine");
        setGitRepository("");
        setBuildPack("nixpacks");
        setZipFile(null);
        setDomain("");
        fetchProject();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsCreatingApp(false);
    }
  };

  const handleCreateDb = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!dbName.trim() || !databaseName.trim()) return;

    setIsCreatingDb(true);
    try {
      const res = await fetch("/api/databases", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          projectId,
          name: dbName,
          type: dbType,
          databaseName,
          databaseUser: databaseUser || (dbType === "postgres" ? "postgres" : "root"),
          rootPassword: rootPassword || undefined,
          exposedPort: dbPort ? parseInt(dbPort, 10) : undefined,
        }),
      });

      if (res.ok) {
        setIsDbModalOpen(false);
        setDbName("");
        setDatabaseName("");
        setDatabaseUser("");
        setRootPassword("");
        setDbPort("");
        fetchProject();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsCreatingDb(false);
    }
  };

  const handleDeploy = async (appId: string) => {
    try {
      await fetch(`/api/applications/${appId}/deploy`, { method: "POST" });
      fetchProject();
    } catch (e) {
      console.error(e);
    }
  };

  const handleStopApp = async (appId: string) => {
    try {
      await fetch(`/api/applications/${appId}/stop`, { method: "POST" });
      fetchProject();
    } catch (e) {
      console.error(e);
    }
  };

  const handleRestartApp = async (appId: string) => {
    try {
      await fetch(`/api/applications/${appId}/restart`, { method: "POST" });
      fetchProject();
    } catch (e) {
      console.error(e);
    }
  };

  if (isLoading) {
    return <div className="text-center py-16 text-slate-400">Loading project environment...</div>;
  }

  if (!project) return null;

  return (
    <div className="space-y-8 animate-in fade-in duration-200">
      {/* Navigation Breadcrumb & Header */}
      <div>
        <Link
          href="/projects"
          className="text-xs font-semibold text-pink-600 hover:underline flex items-center gap-1.5 mb-3 transition-colors"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Back to Projects
        </Link>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200">
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-2xl font-bold tracking-tight text-slate-900">{project.name}</h1>
              <Badge variant="pink" className="text-[11px] font-mono">
                ID: {project.id.substring(0, 8)}
              </Badge>
            </div>
            {project.description && (
              <p className="text-sm text-slate-500 mt-1">{project.description}</p>
            )}
          </div>

          <div className="flex items-center gap-3">
            <Button
              onClick={() => setIsDbModalOpen(true)}
              variant="outline"
              size="sm"
              className="gap-1.5"
            >
              <Database className="h-4 w-4 text-pink-500" />
              New Database
            </Button>
            <Button
              onClick={() => setIsAppModalOpen(true)}
              size="sm"
              className="gap-1.5 bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white shadow-md shadow-emerald-500/20"
            >
              <Plus className="h-4 w-4" />
              Deploy Application
            </Button>
          </div>
        </div>
      </div>

      {/* Applications Section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Layers className="h-5 w-5 text-emerald-600" />
            <h2 className="text-base font-bold text-slate-900">
              Applications ({project.applications?.length || 0})
            </h2>
          </div>
          <Button
            onClick={() => setIsAppModalOpen(true)}
            variant="ghost"
            size="sm"
            className="text-xs text-pink-600 hover:text-pink-700 gap-1 font-semibold"
          >
            <Plus className="h-3.5 w-3.5" />
            Deploy App
          </Button>
        </div>

        {project.applications?.length === 0 ? (
          <Card className="p-8 text-center border-dashed border-slate-300 bg-white">
            <div className="h-12 w-12 rounded-2xl bg-emerald-50 text-emerald-600 flex items-center justify-center mx-auto mb-2 border border-emerald-100">
              <Layers className="h-6 w-6" />
            </div>
            <h3 className="text-base font-bold text-slate-800">No applications in this project yet</h3>
            <p className="text-xs text-slate-500 mt-1 mb-4">
              Deploy from Docker Hub, GitHub (authorized / public), or by uploading a ZIP file.
            </p>
            <Button onClick={() => setIsAppModalOpen(true)} size="sm" variant="success">
              <Plus className="h-4 w-4 mr-1" />
              Deploy First Application
            </Button>
          </Card>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {project.applications.map((app: any) => (
              <Card key={app.id} className="hover:border-emerald-300 hover:shadow-md transition-all flex flex-col justify-between">
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between">
                    <div>
                      <Link
                        href={`/applications/${app.id}`}
                        className="text-base font-bold text-slate-900 hover:text-pink-600 transition-colors"
                      >
                        {app.name}
                      </Link>
                      <div className="text-xs text-slate-500 mt-0.5 font-mono">
                        Port {app.containerPort} {app.exposedPort ? `→ Host :${app.exposedPort}` : ""}
                      </div>
                    </div>
                    <Badge
                      variant={
                        app.status === "running"
                          ? "success"
                          : app.status === "building"
                          ? "warning"
                          : app.status === "error"
                          ? "destructive"
                          : "secondary"
                      }
                      className="capitalize text-[11px]"
                    >
                      {app.status}
                    </Badge>
                  </div>

                  <div className="text-xs text-slate-500 mt-2 line-clamp-1">
                    {app.appType === "image" ? (
                      <span className="font-mono bg-slate-50 px-2 py-1 rounded-md border border-slate-200 text-slate-700">
                        {app.dockerImage || "nginx:alpine"}
                      </span>
                    ) : (
                      <span className="flex items-center gap-1 font-semibold text-slate-700">
                        <GitBranch className="h-3 w-3 text-pink-500" />
                        {app.gitRepository || "Source Deployment"}
                      </span>
                    )}
                  </div>
                </CardHeader>

                <CardContent className="pt-3 border-t border-slate-100 flex items-center justify-between bg-slate-50/50 p-4">
                  <Link href={`/applications/${app.id}`}>
                    <Button variant="outline" size="sm" className="text-xs h-8 px-3">
                      Manage App
                    </Button>
                  </Link>

                  <div className="flex items-center gap-1.5">
                    {app.status === "running" ? (
                      <>
                        <button
                          onClick={() => handleRestartApp(app.id)}
                          title="Restart Container"
                          className="p-1.5 rounded-lg hover:bg-slate-200 text-slate-600 hover:text-slate-900 transition-colors"
                        >
                          <RotateCw className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => handleStopApp(app.id)}
                          title="Stop Container"
                          className="p-1.5 rounded-lg hover:bg-red-50 text-slate-400 hover:text-red-600 transition-colors"
                        >
                          <Square className="h-4 w-4" />
                        </button>
                      </>
                    ) : (
                      <Button
                        onClick={() => handleDeploy(app.id)}
                        size="sm"
                        variant="success"
                        className="h-8 px-3 text-xs gap-1"
                      >
                        <Play className="h-3.5 w-3.5" />
                        Deploy
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>

      {/* Databases Section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Database className="h-5 w-5 text-pink-500" />
            <h2 className="text-base font-bold text-slate-900">
              Managed Databases ({project.databases?.length || 0})
            </h2>
          </div>
          <Button
            onClick={() => setIsDbModalOpen(true)}
            variant="ghost"
            size="sm"
            className="text-xs text-pink-600 hover:text-pink-700 gap-1 font-semibold"
          >
            <Plus className="h-3.5 w-3.5" />
            Add Database
          </Button>
        </div>

        {project.databases?.length === 0 ? (
          <Card className="p-8 text-center border-dashed border-slate-300 bg-white">
            <div className="h-12 w-12 rounded-2xl bg-pink-50 text-pink-500 flex items-center justify-center mx-auto mb-2 border border-pink-100">
              <Database className="h-6 w-6" />
            </div>
            <h3 className="text-base font-bold text-slate-800">No databases in this project</h3>
            <p className="text-xs text-slate-500 mt-1 mb-4">
              1-click provision PostgreSQL, MySQL, Redis, or MongoDB with persistent volume storage.
            </p>
            <Button onClick={() => setIsDbModalOpen(true)} size="sm">
              <Plus className="h-4 w-4 mr-1 text-white" />
              Provision Database
            </Button>
          </Card>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {project.databases.map((db: any) => (
              <Card key={db.id} className="hover:border-pink-300 hover:shadow-md transition-all flex flex-col justify-between">
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between">
                    <div>
                      <div className="text-base font-bold text-slate-900 capitalize">{db.name}</div>
                      <div className="text-xs text-slate-500 font-mono mt-0.5">
                        Internal Port: {db.internalPort}
                      </div>
                    </div>
                    <Badge variant="success" className="capitalize text-[11px]">
                      {db.type}
                    </Badge>
                  </div>
                  <div className="text-xs text-slate-600 mt-2 font-mono bg-slate-50 p-2 rounded-lg border border-slate-200 break-all">
                    Host: cowbox-db-{db.name}
                  </div>
                </CardHeader>
                <CardContent className="pt-3 border-t border-slate-100 flex items-center justify-between text-xs text-slate-600 bg-slate-50/50 p-4">
                  <span>Volume: {db.volumeName || "persistent"}</span>
                  <Link href={`/databases/${db.id}`}>
                    <Button variant="ghost" size="sm" className="h-7 text-xs text-pink-600 font-bold hover:bg-pink-50">
                      Open Workspace & GUI →
                    </Button>
                  </Link>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>

      {/* Deploy Application Modal with Multi-Source Selection */}
      <Modal
        isOpen={isAppModalOpen}
        onClose={() => setIsAppModalOpen(false)}
        title="Deploy New Application"
        description="Choose deployment source: Docker Hub, Public GitHub, Authorized Private Repos, or ZIP upload."
        maxWidth="xl"
      >
        <form onSubmit={handleCreateApp} className="space-y-4">
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-700">Application Identifier *</label>
            <Input
              placeholder="e.g. web-app, auth-api, dashboard"
              value={appName}
              onChange={(e) => setAppName(e.target.value)}
              required
            />
          </div>

          {/* Source Tabs */}
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-700">Deployment Source</label>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {[
                { id: "image", label: "Docker Image", icon: Layers },
                { id: "dockerfile", label: "Raw Dockerfile", icon: FileCode },
                { id: "github_public", label: "GitHub Public", icon: Github },
                { id: "github_auth", label: "GitHub (Token)", icon: Key },
                { id: "zip", label: "Upload ZIP", icon: Upload },
              ].map((s) => {
                const Icon = s.icon;
                const isSelected = sourceMode === s.id;
                return (
                  <button
                    key={s.id}
                    type="button"
                    onClick={() => setSourceMode(s.id as SourceMode)}
                    className={`p-2 rounded-xl border text-xs font-bold transition-all flex flex-col items-center gap-1.5 ${
                      isSelected
                        ? "border-pink-500 bg-pink-50 text-pink-700 shadow-sm"
                        : "border-slate-200 bg-white text-slate-600 hover:bg-slate-50"
                    }`}
                  >
                    <Icon className="h-4 w-4" />
                    <span>{s.label}</span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Docker Image Mode */}
          {sourceMode === "image" && (
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-700">Docker Image Tag *</label>
              <Input
                placeholder="e.g. nginx:alpine, node:20-alpine, ghcr.io/org/repo:latest"
                value={dockerImage}
                onChange={(e) => setDockerImage(e.target.value)}
                required
              />
            </div>
          )}

          {/* Raw Dockerfile Mode with Smart Presets */}
          {sourceMode === "dockerfile" && (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-slate-700">Dockerfile Content *</label>
                <div className="flex gap-1">
                  <button
                    type="button"
                    onClick={async () => {
                      const res = await fetch("/api/ai/dockerfile", {
                        method: "POST",
                        headers: { "Content-Type": "application/json" },
                        body: JSON.stringify({ framework: "nextjs", port: parseInt(containerPort) || 3000 }),
                      });
                      if (res.ok) {
                        const d = await res.json();
                        setDockerfileContent(d.dockerfile);
                        setContainerPort("3000");
                      }
                    }}
                    className="text-[10px] font-bold text-pink-600 hover:bg-pink-50 px-2 py-0.5 rounded border border-pink-200"
                  >
                    + Next.js
                  </button>
                  <button
                    type="button"
                    onClick={async () => {
                      const res = await fetch("/api/ai/dockerfile", {
                        method: "POST",
                        headers: { "Content-Type": "application/json" },
                        body: JSON.stringify({ framework: "fastapi", port: parseInt(containerPort) || 8000 }),
                      });
                      if (res.ok) {
                        const d = await res.json();
                        setDockerfileContent(d.dockerfile);
                        setContainerPort("8000");
                      }
                    }}
                    className="text-[10px] font-bold text-emerald-700 hover:bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200"
                  >
                    + FastAPI
                  </button>
                  <button
                    type="button"
                    onClick={async () => {
                      const res = await fetch("/api/ai/dockerfile", {
                        method: "POST",
                        headers: { "Content-Type": "application/json" },
                        body: JSON.stringify({ framework: "go", port: parseInt(containerPort) || 8080 }),
                      });
                      if (res.ok) {
                        const d = await res.json();
                        setDockerfileContent(d.dockerfile);
                        setContainerPort("8080");
                      }
                    }}
                    className="text-[10px] font-bold text-blue-700 hover:bg-blue-50 px-2 py-0.5 rounded border border-blue-200"
                  >
                    + Go
                  </button>
                </div>
              </div>

              <textarea
                value={dockerfileContent}
                onChange={(e) => setDockerfileContent(e.target.value)}
                className="w-full h-44 p-3 bg-slate-950 font-mono text-xs text-emerald-400 rounded-xl focus:outline-none terminal-scroll leading-relaxed"
                required
              />
            </div>
          )}

          {/* GitHub Public Repo Mode */}
          {sourceMode === "github_public" && (
            <div className="space-y-3">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-700">Public GitHub Repo URL *</label>
                <Input
                  placeholder="https://github.com/facebook/docusaurus"
                  value={gitRepository}
                  onChange={(e) => setGitRepository(e.target.value)}
                  required
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-700">Branch</label>
                  <Input
                    placeholder="main"
                    value={gitBranch}
                    onChange={(e) => setGitBranch(e.target.value)}
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-700">Build Pack</label>
                  <select
                    value={buildPack}
                    onChange={(e) => setBuildPack(e.target.value)}
                    className="flex h-10 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm ring-offset-white file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-slate-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <option value="nixpacks">Nixpacks (Zero Config)</option>
                    <option value="node">Node.js</option>
                    <option value="python">Python</option>
                    <option value="php">PHP Apache</option>
                    <option value="static">Static HTML</option>
                    <option value="dockerfile">Custom Dockerfile</option>
                    <option value="image">Docker Image</option>
                  </select>
                </div>
              </div>
            </div>
          )}

          {/* GitHub Authorized (PAT) Mode */}
          {sourceMode === "github_auth" && (
            <div className="space-y-3">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-700">GitHub Personal Access Token (PAT)</label>
                <div className="flex gap-2">
                  <Input
                    type="password"
                    placeholder="ghp_••••••••••••••••••••"
                    value={githubToken}
                    onChange={(e) => setGithubToken(e.target.value)}
                  />
                  <Button type="button" onClick={handleFetchGithubRepos} isLoading={isLoadingRepos} size="sm" variant="outline">
                    Load Repos
                  </Button>
                </div>
              </div>

              {githubRepos.length > 0 && (
                <div className="space-y-3 mt-3">
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-slate-700">Select Repository</label>
                    <div className="max-h-36 overflow-y-auto border border-slate-200 rounded-xl divide-y divide-slate-100 bg-slate-50">
                      {githubRepos.map((repo) => (
                        <div
                          key={repo.id}
                          onClick={() => handleSelectRepo(repo)}
                          className={`p-2.5 text-xs flex items-center justify-between cursor-pointer hover:bg-pink-50 transition-colors ${
                            gitRepository === repo.cloneUrl ? "bg-pink-100/60 font-bold text-pink-700" : ""
                          }`}
                        >
                          <span>{repo.fullName}</span>
                          <Badge variant="outline" className="text-[10px]">
                            {repo.isPrivate ? "Private" : "Public"}
                          </Badge>
                        </div>
                      ))}
                    </div>
                  </div>
                  
                  {gitRepository && (
                    <div className="grid grid-cols-2 gap-3">
                      <div className="space-y-1.5">
                        <label className="text-xs font-semibold text-slate-700">Branch</label>
                        <Input
                          placeholder="main"
                          value={gitBranch}
                          onChange={(e) => setGitBranch(e.target.value)}
                        />
                      </div>
                      <div className="space-y-1.5">
                        <label className="text-xs font-semibold text-slate-700">Build Pack</label>
                        <select
                          value={buildPack}
                          onChange={(e) => setBuildPack(e.target.value)}
                          className="flex h-10 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm ring-offset-white file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-slate-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                        >
                          <option value="nixpacks">Nixpacks (Zero Config)</option>
                          <option value="node">Node.js</option>
                          <option value="python">Python</option>
                          <option value="php">PHP Apache</option>
                          <option value="static">Static HTML</option>
                          <option value="dockerfile">Custom Dockerfile</option>
                          <option value="image">Docker Image</option>
                        </select>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Upload ZIP Archive Mode */}
          {sourceMode === "zip" && (
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-700">Upload Source Code ZIP Archive *</label>
              <input
                type="file"
                accept=".zip"
                onChange={(e) => {
                  if (e.target.files?.[0]) setZipFile(e.target.files[0]);
                }}
                className="w-full text-xs text-slate-700 file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-xs file:font-bold file:bg-pink-50 file:text-pink-700 hover:file:bg-pink-100 cursor-pointer border border-slate-200 rounded-xl p-2 bg-slate-50"
                required
              />
              <p className="text-[11px] text-slate-500">
                Upload your code archive containing your Dockerfile, Next.js, Node, Python, or Go project.
              </p>
            </div>
          )}

          {/* Ports */}
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-700">Container Port</label>
              <Input
                type="number"
                placeholder="80"
                value={containerPort}
                onChange={(e) => setContainerPort(e.target.value)}
                required
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-700">Host Port (Optional)</label>
              <Input
                type="number"
                placeholder="e.g. 3000"
                value={exposedPort}
                onChange={(e) => setExposedPort(e.target.value)}
              />
            </div>
          </div>

          {/* sslip.io Domain Section */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label className="text-xs font-semibold text-slate-700">
                Wildcard Domain (sslip.io / Traefik SSL)
              </label>
              <button
                type="button"
                onClick={handleAutoGenerateDomain}
                className="text-[11px] font-semibold text-pink-600 hover:underline flex items-center gap-1"
              >
                <Wand2 className="h-3 w-3" />
                Auto sslip.io Domain
              </button>
            </div>
            <Input
              placeholder={`e.g. ${appName || "app"}.${serverIp}.sslip.io`}
              value={domain}
              onChange={(e) => setDomain(e.target.value)}
            />
          </div>

          <div className="flex justify-end gap-2 pt-4 border-t border-slate-100">
            <Button type="button" variant="outline" onClick={() => setIsAppModalOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" isLoading={isCreatingApp} variant="success">
              Deploy Service Now
            </Button>
          </div>
        </form>
      </Modal>

      {/* New Database Modal */}
      <Modal
        isOpen={isDbModalOpen}
        onClose={() => setIsDbModalOpen(false)}
        title="Provision Managed Database"
        description="Launch an isolated containerized database with auto-generated persistent volume."
      >
        <form onSubmit={handleCreateDb} className="space-y-4">
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-700">Database Engine</label>
            <div className="grid grid-cols-4 gap-2">
              {(["postgres", "mysql", "redis", "mongodb"] as const).map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => {
                    setDbType(t);
                    if (!databaseName) setDatabaseName(t === "postgres" ? "main" : "appdb");
                  }}
                  className={`p-2.5 rounded-xl border text-xs font-bold capitalize transition-all ${
                    dbType === t
                      ? "border-pink-500 bg-pink-50 text-pink-700 shadow-sm"
                      : "border-slate-200 bg-white text-slate-600 hover:bg-slate-50"
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-700">Identifier Name *</label>
            <Input
              placeholder="e.g. main-postgres, cache-redis"
              value={dbName}
              onChange={(e) => setDbName(e.target.value)}
              required
            />
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-700">Database Name *</label>
            <Input
              placeholder="e.g. production_db"
              value={databaseName}
              onChange={(e) => setDatabaseName(e.target.value)}
              required
            />
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-slate-700">Root Password (Leave empty for auto-generated)</label>
            <Input
              type="password"
              placeholder="••••••••••••"
              value={rootPassword}
              onChange={(e) => setRootPassword(e.target.value)}
            />
          </div>

          <div className="flex justify-end gap-2 pt-4 border-t border-slate-100">
            <Button type="button" variant="outline" onClick={() => setIsDbModalOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" isLoading={isCreatingDb}>
              Provision Database
            </Button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
